linkis/urls.py
from django.urls import include, path

from . import views

app_name = "linkis"
urlpatterns = [
    path("new", views.LinkiCreateView.as_view(), name="linki_create"),
    path('<slug:pk>',
         views.ArticleDetailView.as_view(), name="article_detail"),
    path("<str:username>/<str:linki_name>/", include([
        path('', views.LinkiDetailView.as_view(), name="linki_detail"),
        path('new', views.TitleCreateView.as_view(), name="article_create"),
        path('<slug:pk>', include([
            path('/history',
                 views.TitleHistoryView.as_view(), name="title_history"),
            path('/edit', views.TitleUpdateView.as_view(), name="title_update"),
            path('', views.TitleDetailView.as_view(), name="title_detail")
        ]))
    ]))
]

roughdrafts/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

urlpatterns = [
    path("home/", TemplateView.as_view(template_name="roughdrafts/home.html")),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include("linkis.urls")),
]

linkis/models.py
from typing import Any, Self

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from msgspec import Struct, convert, to_builtins
from nh3 import clean
from pypandoc import convert_text

from linki.article import BaseArticle as LinkiArticle
from linki.id import ID


class Profile(models.Model):
    editable_fields = ["display_name", "profile_endpoint", "summary"]
    user: User = models.OneToOneField(
        User, on_delete=models.CASCADE)  # type: ignore

    url_endpoint = models.SlugField(null=True, unique=True)
    profile_endpoint = models.SlugField(null=True, blank=True, unique=True)
    display_name = models.CharField(max_length=140, null=True, blank=True)
    summary = models.CharField(max_length=140, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.profile_endpoint = self.get_url_endpoint()
        self.url_endpoint = self.profile_endpoint
        super().save(*args, **kwargs)  # Call the "real" save() method.

    @classmethod
    def get_get_safe_url(cls, user):
        def get_safe_url(url):
            if (url):
                p_endpoint = slugify(url)
                if not cls.objects.exclude(user=user).filter(url_endpoint=p_endpoint).exists():
                    return p_endpoint
        return get_safe_url

    def get_url_endpoint(self):
        get_safe_url = self.get_get_safe_url(self.user)
        safe_url = get_safe_url(self.profile_endpoint)
        if (safe_url):
            return safe_url
        safe_url = get_safe_url(self.display_name)
        if (safe_url):
            return safe_url
        safe_url = get_safe_url(self.user.username)
        if (safe_url):
            return safe_url

    @property
    def profile_name(self):
        if (self.display_name):
            return self.display_name
        return self.user.username

    def __str__(self) -> str:
        return self.user.username


class HasUser(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class HasPrivacy(models.Model):
    class Privacy(models.IntegerChoices):
        PRIVATE = 0
        UNLISTED = 1
        PUBLIC = 2

    privacy = models.IntegerField(
        choices=Privacy.choices, default=Privacy.UNLISTED)

    class Meta:
        abstract = True


class Linki(HasPrivacy, HasUser, models.Model):
    name = models.SlugField()
    editable_fields = ['name']

    def get_absolute_url(self):
        return reverse("linkis:linki_detail", kwargs={
            "username": self.user.username,
            "linki_name": self.name
        })

    """
    TODO
    def get_django_connection(self, style: str):
        return DjangoRepositoryConnection.get_connection(style, self.user, self)
    """


class StructManager(models.Manager):
    model: 'LinkiModel'

    def get_as_struct(self, *args: Any, **kwargs: Any) -> Struct:
        item: LinkiModel = super().get(*args, **kwargs)
        return item.as_linki_type()

    def upsert_from_struct(self, linki: Linki, user: User, id: ID, struct: Struct) -> Struct:
        try:
            return self.update_from_struct(
                linki=linki, user=user, id=id, struct=struct)
        except self.model.DoesNotExist:
            return self.create_from_struct(
                linki=linki, user=user, struct=struct)

    def update_from_struct(self, linki: Linki, user: User, id: ID, struct: Struct) -> Struct:
        item: 'LinkiModel' = super().get(linki=linki, user=user, id=id)
        item.linki = linki
        item.user = user
        item.data = to_builtins(struct)
        item.save()
        return item.as_linki_type()

    def create_from_struct(self, linki: Linki, user: User, struct: Struct) -> Struct:
        item = self.model.from_linki_type(linki, user, struct)
        item.save()
        return item.as_linki_type()


class LinkiModel(HasUser, models.Model):
    linki = models.ForeignKey(Linki, on_delete=models.CASCADE)
    structs = StructManager()
    id = models.CharField(
        max_length=56, default='00000000000000000000000000000000000000000000000000000000',
        primary_key=True,
        editable=False
    )

    data = models.JSONField(default=dict)

    editable_fields = ['data']

    def as_linki_type(self) -> Struct:
        raise NotImplementedError

    @classmethod
    def from_linki_type(cls, linki: Linki, user: User, struct: Struct) -> Self:
        raise NotImplementedError

    def __str__(self) -> str:
        return str(self.as_linki_type())

    class Meta:
        abstract = True


class ArticleBase(LinkiModel, HasPrivacy):
    rendered_content = models.TextField()

    def save(self, *args, **kwargs):
        struct = self.as_linki_type()
        self.rendered_content = self.preview_render(struct.content)
        super().save(*args, **kwargs)  # Call the "real" save() method.

    def get_absolute_url(self):
        return reverse("linkis:article_detail", kwargs={
            "pk": self.id
        })

    def as_linki_type(self) -> LinkiArticle:
        return convert(self.data, type=LinkiArticle)

    @classmethod
    def from_linki_type(cls, linki: Linki, user: User, struct: LinkiArticle) -> Self:
        return cls(
            id=struct.articleId,
            user=user,
            linki=linki,
            data=to_builtins(struct)
        )

    @staticmethod
    def preview_render(content):
        from_f = 'markdown_github-pandoc_title_block'
        html = convert_text(content, 'html', format=from_f,
                            extra_args=['--quiet'])
        return clean(html)

    class Meta:
        abstract = True


class Article(ArticleBase):
    pass


class Title(ArticleBase):
    name = models.SlugField()

    @classmethod
    def from_linki_type(cls, linki: Linki, user: User, struct: LinkiArticle) -> Self:
        item = super().from_linki_type(linki, user, struct)
        item.id = struct.label.labelId
        return item

    def get_absolute_url(self):
        return reverse("linkis:title_detail", kwargs={
            "username": self.user.username,
            "linki_name": self.linki.name,
            "pk": self.name
        })

    def save(self, *args, **kwargs):
        struct = self.as_linki_type()
        self.name = slugify(struct.label.name)
        super().save(*args, **kwargs)  # Call the "real" save() method.

linkis/forms.py
from django import forms


class ArticleForm(forms.Form):
    name = forms.CharField(max_length=250)
    content = forms.CharField(widget=forms.Textarea)

linkis/views.py
from typing import Any, Dict, Optional
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, CreateView, TemplateView
from django.views.generic.edit import FormView
from linki.article import BaseArticle as BLinkiArticle, Article as LinkiArticle, ArticleCollection
from linki.title import TitleCollection
from linki.id import SimpleLabel
from linkis.forms import ArticleForm
from linkis.linki import DjangoConnection

from linkis.models import Article, Linki, Title


class LinkiDetailView(DetailView):
    model = Linki

    def get_object(self, queryset=None):
        user = get_object_or_404(User, username=self.kwargs["username"])
        linki = get_object_or_404(
            Linki, user=user, name=self.kwargs["linki_name"])
        titles = Title.structs.filter(linki=linki).all()
        linki.titles = titles  # type: ignore
        return linki

    """
    def get_object(self, queryset=None):
        if (paste.privacy in [Paste.Privacy.PUBLIC, Paste.Privacy.UNLISTED]):
            return paste
        if (paste.editor == self.request.user):
            return paste
        raise PermissionDenied()
    """


class LinkiCreateView(LoginRequiredMixin, CreateView):
    model = Linki
    fields = Linki.editable_fields

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ArticleDetailView(DetailView):
    model = Article


class TitleDetailView(DetailView):
    model = Title

    def get_object(self, queryset=None):
        user = self.request.user
        linki = self.kwargs["linki_name"]
        linki = get_object_or_404(Linki, user=user, name=linki)
        name = self.kwargs["pk"]
        return Title.structs.get(user=user, linki=linki, name=name)


class TitleHistoryView(TemplateView):
    template_name = "linkis/title_history.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        edits = []
        title: BLinkiArticle = Title.structs.get_as_struct(
            name=self.kwargs["pk"])  # type: ignore
        edits.append(title)
        nex = title.editOf
        while (nex is not None):
            edits.append(nex)
            nex = nex.editOf
        context["edits"] = edits
        return context


class TitleCreateView(LoginRequiredMixin, FormView):
    template_name = "linkis/article_form.html"
    form_class = ArticleForm

    def form_valid(self, form):
        user: User = self.request.user  # type: ignore
        linki = self.kwargs["linki_name"]
        linki = get_object_or_404(Linki, user=user, name=linki)
        article_collection = ArticleCollection(DjangoConnection(
            Article.structs,
            self.request.user,  # type: ignore
            linki
        ))

        title_collection = TitleCollection(DjangoConnection(
            Title.structs,
            self.request.user,  # type: ignore
            linki
        ))

        name = form.cleaned_data["name"]
        content = form.cleaned_data["content"]
        label = SimpleLabel(name)

        article = LinkiArticle(label=label, content=content, editOf=None)
        article_collection.merge_article(article)
        title = title_collection.set_title(article)
        title = Title.structs.get(id=title.label.labelId)
        self.success_url = title.get_absolute_url()
        return super().form_valid(form)


class TitleUpdateView(LoginRequiredMixin, FormView):
    template_name = "linkis/article_form.html"
    form_class = ArticleForm

    def get_initial(self) -> Dict[str, Any]:
        user = self.request.user
        linki = self.kwargs["linki_name"]
        pk = self.kwargs["pk"]
        linki = get_object_or_404(Linki, user=user, name=linki)
        title = get_object_or_404(
            Title, linki=linki, user=user, name=pk)
        return {'name': title.name, 'content': title.data["content"]}

    def form_valid(self, form):
        user = self.request.user
        linki = self.kwargs["linki_name"]
        linki = get_object_or_404(Linki, user=user, name=linki)
        article_collection = ArticleCollection(DjangoConnection(
            Article.structs,
            self.request.user,  # type: ignore
            linki
        ))

        title_collection = TitleCollection(DjangoConnection(
            Title.structs,
            self.request.user,  # type: ignore
            linki
        ))

        name = form.cleaned_data["name"]
        content = form.cleaned_data["content"]
        label = SimpleLabel(name)

        title = title_collection.get_title(label)
        edit_of = None
        if (title):
            edit_of = article_collection.get_article(title.articleId)

        article = LinkiArticle(label=label, content=content, editOf=edit_of)
        title_collection.set_title(article)
        article_collection.merge_article(article)

        article = Article.structs.get(id=article.articleId)
        self.success_url = article.get_absolute_url()
        return super().form_valid(form)

linkis/templates/linkis/article_detail.html
<div>{{ object.data }}</div>
<div>{{ object.content }}</div>
<div>{{ object.as_linki_type.label.labelId }}</div>
<div>{{ object.as_linki_type.articleId }}</div>

linkis/templates/linkis/article_form.html
{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
  </form>
{% endblock body %}

linkis/templates/linkis/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="description" content="Linkis" />
    <meta name="keywords" content="linkis hosting" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block head_title %}
        Roughdrafts XYZ
      {% endblock head_title %}
    </title>
    {% block extra_head %}
    {% endblock extra_head %}
  </head>
  <body>
    <header>
      <nav>
        {% block nav %}
        {% endblock nav %}
      </nav>
    </header>
    {% block body %}
      <main>
        <article>
          <header>
            <h1>
              {% block page_title %}
              {% endblock page_title %}
            </h1>
            {% block extra_header %}
            {% endblock extra_header %}
          </header>
          {% block content %}
          {% endblock content %}
        </article>
      </main>
    {% endblock body %}
    <footer>
      {% block footer %}
      {% endblock footer %}
    </footer>
  </body>
</html>

linkis/templates/linkis/linki_detail.html
{% extends "linkis/base.html" %}
{% block content %}
    {{ linki.name }}
    <ul>
        {% for title in linki.titles %}
            <li>
                <a href="{{ title.as_linki_type.label.name }}">{{ title.as_linki_type.label.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

linkis/templates/linkis/linki_form.html
{% extends "linkis/base.html" %}
{% load linki_nav %}
{% load static %}
{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">Make new Linki</button>
  </form>
{% endblock body %}

linkis/templates/linkis/paste_confirm_delete.html
{% extends "linkis/base.html" %}
{% load linki_nav %}
{% block page_title %}
  Deleting {{ linki.title }}
{% endblock page_title %}
{% block extra_header %}
  <p>{{ linki.summary }}</p>
{% endblock extra_header %}
{% block nav %}
  {% nav %}
  <li>
    <a href="{% url 'linkis:detail' linki.editor.profile.url_endpoint linki.url_endpoint %}">cancel</a>
  </li>
{% endnav %}
{% endblock nav %}
{% block content %}
  <details>
    <summary>Content</summary>
    {% autoescape off %}
      {{ linki.rendered_content }}
    {% endautoescape %}
  </details>
  <form method="post">
    {% csrf_token %}
    {{ form.expected_endpoint }}
    {{ form.non_field_errors }}
    <div>
      <label>
        please enter <strong>{{ linki.url_endpoint }}</strong> to confirm:
        {{ form.url_endpoint.errors }}
        {{ form.url_endpoint }}
      </label>
    </div>
    <footer>
      <button type="submit" name="action">Delete</button>
      <a href="{% url 'linkis:detail' linki.editor.profile.url_endpoint linki.url_endpoint %}">
        <button type="button">Cancel</button>
      </a>
    </footer>
  </form>
{% endblock content %}

linkis/templates/linkis/profile_confirm_delete.html
{% extends "linkis/base.html" %}
{% load linki_nav %}
{% block page_title %}
  Deleting Your Account
{% endblock page_title %}
{% block extra_header %}
{% endblock extra_header %}
{% block nav %}
  {% nav %}
  <li>
    <a href="{% url 'linkis:profile.edit' %}">cancel</a>
  </li>
{% endnav %}
{% endblock nav %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.expected_endpoint }}
    {{ form.non_field_errors }}
    <div>
      <label>
        <div>
          <p>
            please enter <strong>{{ profile.url_endpoint }}</strong> to confirm:
          </p>
          {{ form.url_endpoint.errors }}
        </div>
        {{ form.url_endpoint }}
      </label>
    </div>
    <footer>
      <button type="submit" name="action">Delete</button>
      <a href="{% url 'linkis:profile.edit' %}">
        <button type="button">Cancel</button>
      </a>
    </footer>
  </form>
{% endblock content %}

linkis/templates/linkis/profile_detail.html
{% extends "linkis/base.html" %}
{% load linki_nav %}
{% block nav %}
  {% nav %}
  <li>
    <a href="{% url "linkis:create" %}">create new linki</a>
  </li>
  <li>
    <a href="{% url "linkis:profile.edit" %}">update profile</a>
  </li>
{% endnav %}
{% endblock nav %}
{% block page_title %}
  {{ profile.profile_name }}
{% endblock page_title %}
{% block extra_header %}
  <p>{{ profile.summary }}</p>
{% endblock extra_header %}
{% block content %}
  {% if profile.linkis %}
    {% for linki in profile.linkis %}
      <section>
        <a href="{% url 'linkis:detail' profile.url_endpoint linki.url_endpoint %}">
          <h3>{{ linki.title }}</h3>
        </a>
        <p>
          {% if linki.summary %}
            {{ linki.summary }}
          {% else %}
            {{ linki.content|truncatechars:140 }}
          {% endif %}
        </p>
      </section>
    {% endfor %}
  {% else %}
    <section>
      No linkis are available.
    </section>
  {% endif %}
{% endblock content %}

linkis/templates/linkis/profile_form.html
{% extends "linkis/base.html" %}
{% load linki_nav %}
{% block page_title %}
  Updating User Settings
{% endblock page_title %}
{% block nav %}
  {% nav %}
{% endnav %}
{% endblock nav %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <footer>
      <button type="submit" name="action">Save Profile</button>
      <a href="{% url 'linkis:profile' profile.url_endpoint %}">
        <button type="button">Cancel</button>
      </a>
    </footer>
  </form>
  <section>
    <header>
      <h2>Download Notes</h2>
    </header>
    <p>
      <a href="{% url 'linkis:profile.download' %}">
        <button type="button">Download Notes</button>
      </a>
      <aside>
        (This will download a zip file of all your notes.)
      </aside>
    </p>
  </section>
  <section>
    <header>
      <h2>Account Management</h2>
    </header>
    {% block extra_user_settings %}
    {% endblock extra_user_settings %}
    <hr />
    <p>
      <a href="{% url 'linkis:profile.delete' %}">
        <button type="button">Delete Account and Linkis</button>
      </a>
      <aside>
        (This will bring you to a confirmation page before deleting anything.)
      </aside>
    </p>
  </section>
{% endblock content %}

linkis/templates/linkis/title_detail.html
{% block nav %}
    <a href="{% url "linkis:title_update" object.user object.linki.name object.name %}">edit</a>
    <a href="{% url "linkis:title_history" object.user object.linki.name object.name %}">history</a>
{% endblock nav %}
<div>{{ object.data }}</div>
<div>{{ object.as_linki_type }}</div>
<div>{{ object.content }}</div>
<div>{{ object.as_linki_type.label.labelId }}</div>
<div>{{ object.as_linki_type.articleId }}</div>

linkis/templates/linkis/title_history.html
<ul>
    {% for edit in edits %}
        <li>
            <a href="{% url 'linkis:article_detail' edit.articleId %}">{{ edit.articleId|truncatechars:6 }} {{ edit.name }}</a>
        </li>
    {% endfor %}
</ul>

linkis/templates/linkis/zip_html.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{ linki.title }}</title>
        <meta name="description" content="{{ linki.summary }}" />
        <meta name="keywords" content="{{ linki.summary }}" />
        <meta name="author" content="{{ linki.editor }}" />
        <meta name="created" content="{{ linki.created_at }}" />
        <meta name="updated" content="{{ linki.updated_at }}" />
    </head>
    <body>
        <main>
            <article>
                {% autoescape off %}
                    {{ linki.rendered_content }}
                {% endautoescape %}
            </article>
        </main>
    </body>
</html>